import type { WorkflowSpec } from './types';

export const businessCopyWorkflow: WorkflowSpec = {
  id: 'workflow-business-copy',
  name: '商业文案生产链路',
  description: '面向产品发布、品牌推广和销售文案，覆盖简报、定位、卖点、成稿、审核和导出。',
  workspaceType: 'business-copy',
  defaultStageId: 'brief',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'brief',
      title: '项目简报',
      description: '确认产品、渠道和交付目标。',
      component: 'business-copy',
      requiredInputs: ['productName', 'category', 'features'],
      outputs: ['productBrief'],
      aiActions: [{ id: 'generate-brief', label: '生成简报', type: 'generate', primary: true }],
    },
    {
      id: 'positioning',
      title: '产品定位',
      description: '整理卖点、受众和转化目标。',
      component: 'business-copy',
      requiredInputs: ['productBrief'],
      outputs: ['positioningNotes'],
      aiActions: [{ id: 'generate-positioning', label: '生成定位', type: 'generate', primary: true }],
    },
    {
      id: 'selling-points',
      title: '卖点工厂',
      description: '把功能转换成利益点和信任理由。',
      component: 'business-copy',
      requiredInputs: ['positioningNotes'],
      outputs: ['sellingPoints'],
      aiActions: [{ id: 'generate-selling-points', label: '生成卖点', type: 'outline', primary: true }],
    },
    {
      id: 'copy',
      title: '文案工厂',
      description: '生成标题、正文和行动指令。',
      component: 'business-copy',
      requiredInputs: ['sellingPoints'],
      outputs: ['copy'],
      aiActions: [{ id: 'generate-copy', label: '生成文案', type: 'generate', primary: true }],
    },
    {
      id: 'review',
      title: '审核工厂',
      description: '检查敏感词、平台规范和转化表达。',
      component: 'business-copy',
      requiredInputs: ['copy'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-copy', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 成品。',
      component: 'business-copy',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-copy', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
