import type { WorkflowSpec } from './types';

export const comicDramaOutlineWorkflow: WorkflowSpec = {
  id: 'comic-drama-outline-workflow',
  name: 'AI 漫剧大纲工作流',
  description: '适用于故事设定、人物、分集和 Media Master JSON 预留导出的流程。',
  workspaceType: 'comic-drama-outline',
  defaultStageId: 'overview',
  exportTargets: ['markdown', 'txt', 'json', 'media-master-json'],
  stages: [
    {
      id: 'overview',
      title: '项目总览',
      description: '先确认题材、冲突和故事方向。',
      component: 'comic-drama',
      requiredInputs: ['genre', 'theme', 'conflict'],
      outputs: ['premise'],
      aiActions: [{ id: 'generate-premise', label: '生成故事设定', type: 'generate', primary: true }],
    },
    {
      id: 'settings',
      title: '故事设定',
      description: '整理世界观、题材、冲突和故事卖点。',
      component: 'comic-drama',
      requiredInputs: ['genre', 'theme', 'conflict'],
      outputs: ['premise'],
      aiActions: [{ id: 'refine-premise', label: '整理设定', type: 'generate', primary: true }],
    },
    {
      id: 'materials',
      title: '人物资料',
      description: '整理主角、配角和关系网。',
      component: 'comic-drama',
      requiredInputs: ['characters'],
      outputs: ['characterSheet'],
      aiActions: [{ id: 'generate-characters', label: '生成人物卡', type: 'generate', primary: true }],
    },
    {
      id: 'outline',
      title: '分集大纲',
      description: '拆分剧情节奏、转折和悬念。',
      component: 'comic-drama',
      requiredInputs: ['premise', 'characters'],
      outputs: ['episodes'],
      aiActions: [{ id: 'generate-episodes', label: '生成分集大纲', type: 'outline', primary: true }],
    },
    {
      id: 'editor',
      title: '场景生产',
      description: '推进场景、台词和剧情节拍。',
      component: 'comic-drama',
      requiredInputs: ['episodes'],
      outputs: ['sceneDraft'],
      aiActions: [{ id: 'generate-scenes', label: '生成场景', type: 'generate', primary: true }],
    },
    {
      id: 'rewrite',
      title: '冲突强化',
      description: '加强戏剧冲突、节奏和反转。',
      component: 'comic-drama',
      requiredInputs: ['sceneDraft'],
      outputs: ['rewriteCandidate'],
      aiActions: [{ id: 'rewrite-scenes', label: '强化冲突', type: 'rewrite', primary: true }],
    },
    {
      id: 'review',
      title: '一致性审核',
      description: '检查人物、世界观和节奏一致性。',
      component: 'comic-drama',
      requiredInputs: ['sceneDraft'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-outline', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'versions',
      title: '版本记录',
      description: '查看大纲、场景和修订历史。',
      component: 'comic-drama',
      requiredInputs: ['versions'],
      outputs: ['versionLog'],
      aiActions: [{ id: 'snapshot', label: '保存快照', type: 'generate', primary: true }],
    },
    {
      id: 'export',
      title: 'Media Master 导出',
      description: '预留 JSON 结构，便于后续接入媒体链路。',
      component: 'comic-drama',
      requiredInputs: ['document'],
      outputs: ['mediaMasterJson'],
      aiActions: [{ id: 'export-media', label: '导出 JSON', type: 'export', primary: true }],
    },
  ],
};
