import type { WorkflowSpec } from './types';

export const novelWorkflow: WorkflowSpec = {
  id: 'workflow-novel',
  name: '小说生产链路',
  description: '面向长篇小说和连载故事，覆盖设定、世界观、人物、章节、正文、改写、审核和导出。',
  workspaceType: 'generic-text',
  defaultStageId: 'brief',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'brief',
      title: '项目简报',
      description: '先确认题材、目标读者、风格约束和交付节奏。',
      component: 'generic',
      requiredInputs: ['genre', 'audience', 'tone'],
      outputs: ['projectBrief'],
      aiActions: [{ id: 'generate-brief', label: '生成简报', type: 'generate', primary: true }],
    },
    {
      id: 'worldbuilding',
      title: '世界观设定',
      description: '整理时代背景、势力关系、规则系统和叙事边界。',
      component: 'generic',
      requiredInputs: ['projectBrief'],
      outputs: ['worldbuildingNotes'],
      aiActions: [{ id: 'generate-worldbuilding', label: '生成世界观', type: 'outline', primary: true }],
    },
    {
      id: 'characters',
      title: '人物设定',
      description: '建立主角、配角、关系网和角色弧线。',
      component: 'generic',
      requiredInputs: ['projectBrief'],
      outputs: ['characterSheet'],
      aiActions: [{ id: 'generate-characters', label: '生成人物', type: 'generate', primary: true }],
    },
    {
      id: 'outline',
      title: '章节大纲',
      description: '把故事拆成章节目标、冲突推进和转折节点。',
      component: 'generic',
      requiredInputs: ['worldbuildingNotes', 'characterSheet'],
      outputs: ['outline'],
      aiActions: [{ id: 'generate-outline', label: '生成大纲', type: 'outline', primary: true }],
    },
    {
      id: 'draft',
      title: '正文草稿',
      description: '基于章节目标输出可继续扩写的正文。',
      component: 'generic',
      requiredInputs: ['outline'],
      outputs: ['draft'],
      aiActions: [{ id: 'generate-draft', label: '生成正文', type: 'generate', primary: true }],
    },
    {
      id: 'revise',
      title: '改写工厂',
      description: '支持压缩、扩写、重写和语气微调。',
      component: 'generic',
      requiredInputs: ['draft'],
      outputs: ['rewriteCandidate'],
      aiActions: [{ id: 'rewrite-draft', label: '生成改写', type: 'rewrite', primary: true }],
    },
    {
      id: 'review',
      title: '审核工厂',
      description: '检查人物一致性、剧情连贯性和文本风险。',
      component: 'generic',
      requiredInputs: ['draft'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-draft', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 成品。',
      component: 'generic',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-file', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
