import type { WorkflowSpec } from './types';

export const businessBpWorkflow: WorkflowSpec = {
  id: 'workflow-business-bp',
  name: '商业 BP 生产链路',
  description: '面向商业计划书和融资材料，覆盖概览、市场、模式、财务、路演稿、审核和导出。',
  workspaceType: 'generic-text',
  defaultStageId: 'overview',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'overview',
      title: '项目概览',
      description: '确认项目目标、行业背景和交付范围。',
      component: 'generic',
      requiredInputs: ['projectGoal', 'industry', 'scope'],
      outputs: ['projectBrief'],
      aiActions: [{ id: 'generate-overview', label: '生成概览', type: 'generate', primary: true }],
    },
    {
      id: 'market-analysis',
      title: '市场分析',
      description: '整理市场规模、竞品和切入机会。',
      component: 'generic',
      requiredInputs: ['projectBrief'],
      outputs: ['marketAnalysis'],
      aiActions: [{ id: 'generate-market-analysis', label: '生成市场分析', type: 'outline', primary: true }],
    },
    {
      id: 'business-model',
      title: '商业模式',
      description: '描述收入来源、成本结构和增长路径。',
      component: 'generic',
      requiredInputs: ['marketAnalysis'],
      outputs: ['businessModel'],
      aiActions: [{ id: 'generate-business-model', label: '生成商业模式', type: 'generate', primary: true }],
    },
    {
      id: 'financial-forecast',
      title: '财务预测',
      description: '生成收入、成本、利润和回收期的描述。',
      component: 'generic',
      requiredInputs: ['businessModel'],
      outputs: ['financialForecast'],
      aiActions: [{ id: 'generate-forecast', label: '生成财务预测', type: 'generate', primary: true }],
    },
    {
      id: 'pitch-deck',
      title: '路演稿',
      description: '把核心观点整理成更适合演示的表达。',
      component: 'generic',
      requiredInputs: ['financialForecast'],
      outputs: ['pitchDeck'],
      aiActions: [{ id: 'generate-pitch', label: '生成路演稿', type: 'generate', primary: true }],
    },
    {
      id: 'review',
      title: '审核工厂',
      description: '检查商业逻辑、财务口径和表达风险。',
      component: 'generic',
      requiredInputs: ['pitchDeck'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-bp', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 版本。',
      component: 'generic',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-bp', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
