import type { WorkflowSpec } from './types';

export const documentWorkflow: WorkflowSpec = {
  id: 'workflow-document',
  name: '项目文档生产链路',
  description: '面向需求文档、合同草案和方案说明，覆盖信息收集、资料整理、条款、风险、格式化和导出。',
  workspaceType: 'generic-text',
  defaultStageId: 'intake',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'intake',
      title: '信息收集',
      description: '确认目标、边界、背景和交付要求。',
      component: 'generic',
      requiredInputs: ['title', 'summary'],
      outputs: ['documentBrief'],
      aiActions: [{ id: 'generate-intake', label: '生成信息摘要', type: 'generate', primary: true }],
    },
    {
      id: 'sources',
      title: '资料整理',
      description: '整理参考资料、附件和原始素材。',
      component: 'generic',
      requiredInputs: ['documentBrief'],
      outputs: ['sourceNotes'],
      aiActions: [{ id: 'generate-sources', label: '整理资料', type: 'outline', primary: true }],
    },
    {
      id: 'clauses',
      title: '条款工厂',
      description: '生成正文条款、章节结构和约束条件。',
      component: 'generic',
      requiredInputs: ['sourceNotes'],
      outputs: ['clausesDraft'],
      aiActions: [{ id: 'generate-clauses', label: '生成条款', type: 'generate', primary: true }],
    },
    {
      id: 'risk-review',
      title: '风险审核',
      description: '检查歧义、缺口和潜在风险。',
      component: 'generic',
      requiredInputs: ['clausesDraft'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-document', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'format',
      title: '格式化',
      description: '整理章节层级、标题和导出格式。',
      component: 'generic',
      requiredInputs: ['clausesDraft'],
      outputs: ['formattedDocument'],
      aiActions: [{ id: 'format-document', label: '格式化文档', type: 'generate', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 版本。',
      component: 'generic',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-document', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
