import type { WorkflowSpec } from './types';

export const investmentCopyWorkflow: WorkflowSpec = {
  id: 'workflow-investment-copy',
  name: '招商文案生产链路',
  description: '面向加盟招商和平台招商内容，覆盖定位、政策、卖点、收益、落地页、审核和导出。',
  workspaceType: 'business-copy',
  defaultStageId: 'positioning',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'positioning',
      title: '品牌定位',
      description: '先确定招商对象、品牌定位和合作前提。',
      component: 'generic',
      requiredInputs: ['brand', 'audience', 'positioning'],
      outputs: ['positioningBrief'],
      aiActions: [{ id: 'generate-positioning', label: '生成定位', type: 'generate', primary: true }],
    },
    {
      id: 'policy',
      title: '招商政策',
      description: '整理合作政策、加盟门槛和支持内容。',
      component: 'generic',
      requiredInputs: ['positioningBrief'],
      outputs: ['policyNotes'],
      aiActions: [{ id: 'generate-policy', label: '生成政策', type: 'outline', primary: true }],
    },
    {
      id: 'offer',
      title: '产品卖点',
      description: '输出产品优势、差异点和成交理由。',
      component: 'generic',
      requiredInputs: ['policyNotes'],
      outputs: ['sellingPoints'],
      aiActions: [{ id: 'generate-offer', label: '生成卖点', type: 'generate', primary: true }],
    },
    {
      id: 'revenue-model',
      title: '收益模型',
      description: '说明回报逻辑、收入来源和盈利结构。',
      component: 'generic',
      requiredInputs: ['sellingPoints'],
      outputs: ['revenueModel'],
      aiActions: [{ id: 'generate-revenue-model', label: '生成收益模型', type: 'generate', primary: true }],
    },
    {
      id: 'landing-page',
      title: '招商落地页',
      description: '把招商信息整理为更适合落地页的成稿。',
      component: 'generic',
      requiredInputs: ['revenueModel'],
      outputs: ['landingPageDraft'],
      aiActions: [{ id: 'generate-landing-page', label: '生成落地页', type: 'generate', primary: true }],
    },
    {
      id: 'review',
      title: '审核工厂',
      description: '检查招商承诺、表达风险和平台合规。',
      component: 'generic',
      requiredInputs: ['landingPageDraft'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-investment', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 版本。',
      component: 'generic',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-investment', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
