import type { WorkflowSpec } from './types';

export const shortVideoScriptWorkflow: WorkflowSpec = {
  id: 'workflow-short-drama',
  name: '短剧生产链路',
  description: '面向短剧、短视频脚本和分集内容，覆盖选题、结构、剧本、改写、审核和导出。',
  workspaceType: 'short-video-script',
  defaultStageId: 'concept',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'concept',
      title: '项目简报',
      description: '确认题材、平台和受众，锁定故事方向。',
      component: 'short-video',
      requiredInputs: ['topic', 'platform', 'audience'],
      outputs: ['projectBrief'],
      aiActions: [{ id: 'generate-brief', label: '生成简报', type: 'generate', primary: true }],
    },
    {
      id: 'outline',
      title: '分集大纲',
      description: '拆分分集节奏、冲突和钩子。',
      component: 'short-video',
      requiredInputs: ['projectBrief'],
      outputs: ['outline'],
      aiActions: [{ id: 'generate-outline', label: '生成大纲', type: 'outline', primary: true }],
    },
    {
      id: 'script',
      title: '剧本工厂',
      description: '生成对白、场景和镜头节奏。',
      component: 'short-video',
      requiredInputs: ['outline'],
      outputs: ['scriptDraft'],
      aiActions: [{ id: 'generate-script', label: '生成剧本', type: 'generate', primary: true }],
    },
    {
      id: 'revise',
      title: '改写工厂',
      description: '进行口语化、压缩或风格重写。',
      component: 'short-video',
      requiredInputs: ['scriptDraft'],
      outputs: ['rewriteCandidate'],
      aiActions: [{ id: 'rewrite-script', label: '生成改写', type: 'rewrite', primary: true }],
    },
    {
      id: 'review',
      title: '审核工厂',
      description: '检查节奏、钩子和平台敏感词。',
      component: 'short-video',
      requiredInputs: ['scriptDraft'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-script', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 成品。',
      component: 'short-video',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-script', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
