import type { WorkflowSpec } from './types';

export const xiaohongshuWorkflow: WorkflowSpec = {
  id: 'workflow-xiaohongshu',
  name: '小红书生产链路',
  description: '面向种草笔记和社媒内容，覆盖选题、钩子、结构、正文、标题、标签、审核和导出。',
  workspaceType: 'business-copy',
  defaultStageId: 'topic',
  exportTargets: ['markdown', 'txt', 'json'],
  stages: [
    {
      id: 'topic',
      title: '选题工厂',
      description: '确认种草方向、目标人群和内容场景。',
      component: 'generic',
      requiredInputs: ['topic', 'audience', 'scene'],
      outputs: ['topicBrief'],
      aiActions: [{ id: 'generate-topic', label: '生成选题', type: 'generate', primary: true }],
    },
    {
      id: 'hook',
      title: '开头钩子',
      description: '生成更容易停留的开头和反差表达。',
      component: 'generic',
      requiredInputs: ['topicBrief'],
      outputs: ['hookDraft'],
      aiActions: [{ id: 'generate-hook', label: '生成钩子', type: 'generate', primary: true }],
    },
    {
      id: 'structure',
      title: '内容结构',
      description: '拆分正文节奏、信息顺序和卖点分布。',
      component: 'generic',
      requiredInputs: ['hookDraft'],
      outputs: ['structureOutline'],
      aiActions: [{ id: 'generate-structure', label: '生成结构', type: 'outline', primary: true }],
    },
    {
      id: 'body',
      title: '正文工厂',
      description: '输出完整正文草稿与可润色版本。',
      component: 'generic',
      requiredInputs: ['structureOutline'],
      outputs: ['bodyDraft'],
      aiActions: [{ id: 'generate-body', label: '生成正文', type: 'generate', primary: true }],
    },
    {
      id: 'titles',
      title: '标题工厂',
      description: '批量生成多版本标题。',
      component: 'generic',
      requiredInputs: ['bodyDraft'],
      outputs: ['titleVariants'],
      aiActions: [{ id: 'generate-titles', label: '生成标题', type: 'generate', primary: true }],
    },
    {
      id: 'hashtags',
      title: '标签工厂',
      description: '生成标签、禁用词提示和发布建议。',
      component: 'generic',
      requiredInputs: ['bodyDraft'],
      outputs: ['tagSet'],
      aiActions: [{ id: 'generate-hashtags', label: '生成标签', type: 'generate', primary: true }],
    },
    {
      id: 'review',
      title: '审核工厂',
      description: '检查敏感词、平台表达和内容一致性。',
      component: 'generic',
      requiredInputs: ['bodyDraft'],
      outputs: ['reviewIssues'],
      aiActions: [{ id: 'review-post', label: '执行审核', type: 'review', primary: true }],
    },
    {
      id: 'export',
      title: '导出中心',
      description: '导出 Markdown、TXT 或 JSON 版本。',
      component: 'generic',
      requiredInputs: ['document'],
      outputs: ['exportFile'],
      aiActions: [{ id: 'export-post', label: '执行导出', type: 'export', primary: true }],
    },
  ],
};
