import type { TemplateSpec } from './types';

export const templateRegistry: TemplateSpec[] = [
  {
    id: 'short-drama-episode-outline',
    name: '短剧分集大纲',
    category: 'short_drama',
    description: '按集数拆分钩子、付费点和结尾悬念，适合快节奏短剧前期搭骨架。',
    inputSchema: ['topic', 'platform', 'audience', 'episodeCount'],
    promptRecipe: ['锁定题材', '生成钩子', '拆分分集大纲'],
    outputSchema: ['episodeOutline', 'hookPlan', 'hookUpgrade'],
    exportFormats: ['markdown', 'txt', 'json'],
    targetApp: 'text-master',
    workflowId: 'short-video-script-workflow',
    workspaceType: 'short-video-script',
    projectType: 'short_drama',
    summary: '按集数拆分一钩、二钩、付费点和结尾悬念，适合快节奏短剧前期搭骨架。',
    scenario: '短剧立项 / 分集结构 / 投流节奏',
    output: '分集大纲、钩子规则、冲突升级表',
    tags: ['强钩子', '付费点', '分集结构'],
    mockParams: {
      template: 'short-drama-episode-outline',
      type: 'short_drama',
      strategy: 'fast-hook-outline',
    },
  },
  {
    id: 'novel-chapter-generator',
    name: '小说章节生成',
    category: 'novel',
    description: '围绕世界观、人物动机和章节目标，生成稳定的长线章节草稿。',
    inputSchema: ['worldview', 'characters', 'chapterGoal'],
    promptRecipe: ['整理设定', '生成章节目标', '输出章节草稿'],
    outputSchema: ['chapterGoal', 'sceneBreakdown', 'draft'],
    exportFormats: ['markdown', 'txt', 'json'],
    targetApp: 'text-master',
    workflowId: 'generic-text-workflow',
    workspaceType: 'generic-text',
    projectType: 'novel',
    summary: '从世界观、人物动机和章节目标出发，生成稳定的长线章节草稿。',
    scenario: '长篇连载 / 章节草稿 / 世界观推进',
    output: '章节目标、场景拆分、正文候选',
    tags: ['长篇', '章节', '人物线'],
    mockParams: {
      template: 'novel-chapter-generator',
      type: 'novel',
      strategy: 'chapter-draft',
    },
  },
  {
    id: 'xiaohongshu-seeding-copy',
    name: '小红书种草文案',
    category: 'xiaohongshu',
    description: '围绕人群痛点、产品卖点和生活化表达，生成适合小红书发布的种草文案。',
    inputSchema: ['product', 'audience', 'scenario', 'keywords'],
    promptRecipe: ['提炼卖点', '生成标题组', '生成正文'],
    outputSchema: ['titleSet', 'postCopy', 'tags', 'banWordsHint'],
    exportFormats: ['markdown', 'txt', 'json'],
    targetApp: 'text-master',
    workflowId: 'business-copy-workflow',
    workspaceType: 'business-copy',
    projectType: 'business_copy',
    summary: '围绕人群痛点、产品卖点和生活化表达，生成适合小红书发布的种草文案。',
    scenario: '消费品种草 / 笔记标题 / 卖点转译',
    output: '标题组、正文、标签、禁用词提示',
    tags: ['小红书', '种草', '转化'],
    mockParams: {
      template: 'xiaohongshu-seeding-copy',
      type: 'business_copy',
      platform: 'xiaohongshu',
    },
  },
  {
    id: 'readme-generator',
    name: 'README 生成',
    category: 'readme',
    description: '把项目定位、安装方式、运行流程、目录结构和验收标准整理成可交付 README。',
    inputSchema: ['projectName', 'installSteps', 'runSteps', 'directoryStructure'],
    promptRecipe: ['梳理定位', '整理步骤', '输出 README'],
    outputSchema: ['readmeSections', 'usageNotes', 'verificationChecklist'],
    exportFormats: ['markdown', 'txt', 'json'],
    targetApp: 'text-master',
    workflowId: 'generic-text-workflow',
    workspaceType: 'generic-text',
    projectType: 'document',
    summary: '将项目定位、安装方式、运行流程、目录结构和验收标准整理成可交付 README。',
    scenario: '开源项目 / 内部工具 / 产品说明',
    output: 'README.md 结构、命令区、验收标准',
    tags: ['README', '文档', '交付'],
    mockParams: {
      template: 'readme-generator',
      type: 'document',
      format: 'markdown',
    },
  },
  {
    id: 'bp-copy-generator',
    name: 'BP 文案生成',
    category: 'business_copy',
    description: '将商业模式、目标市场、产品优势和融资叙事压缩成清晰的 BP 表达。',
    inputSchema: ['brand', 'market', 'product', 'fundraisingGoal'],
    promptRecipe: ['整理商业模式', '提炼卖点', '生成 BP'],
    outputSchema: ['oneSentencePitch', 'pageCopy', 'talkTrack'],
    exportFormats: ['markdown', 'txt', 'json'],
    targetApp: 'story-forge',
    workflowId: 'business-copy-workflow',
    workspaceType: 'business-copy',
    projectType: 'business_copy',
    summary: '将商业模式、目标市场、产品优势和融资叙事压缩成清晰的 BP 表达。',
    scenario: '融资 BP / 路演稿 / 商业叙事',
    output: '一句话定位、页面文案、路演话术',
    tags: ['BP', '商业', '叙事'],
    mockParams: {
      template: 'bp-copy-generator',
      type: 'business_copy',
      strategy: 'business-narrative',
    },
  },
  {
    id: 'product-intro-copy',
    name: '产品介绍文案',
    category: 'business_copy',
    description: '将功能、价值、场景和行动指令整理成官网、落地页或产品手册文案。',
    inputSchema: ['productName', 'features', 'benefits', 'cta'],
    promptRecipe: ['提炼功能', '转译利益', '输出渠道文案'],
    outputSchema: ['positioning', 'benefitCopy', 'ctaCopy'],
    exportFormats: ['markdown', 'txt', 'json'],
    targetApp: 'text-master',
    workflowId: 'business-copy-workflow',
    workspaceType: 'business-copy',
    projectType: 'business_copy',
    summary: '把功能、价值、场景和行动指令整理成官网、落地页或产品手册文案。',
    scenario: '产品官网 / 落地页 / 销售资料',
    output: '产品定位、功能卖点、CTA 文案',
    tags: ['产品', '介绍', '转化'],
    mockParams: {
      template: 'product-intro-copy',
      type: 'business_copy',
      strategy: 'product-positioning',
    },
  },
];

export function getTemplateById(templateId?: string): TemplateSpec | undefined {
  return templateRegistry.find((template) => template.id === templateId);
}

export function getTemplatesByProjectType(projectType: string): TemplateSpec[] {
  return templateRegistry.filter((template) => template.projectType === projectType);
}
